### ISSUE TITLE
bare imports 'npm:mongodb' 'jsr:@db/mongo' aren't functioning

### ISSUE THREAD

**Issue by akacase** [rscarson/rustyscript#297]
**Describe the bug**

I'm developing a plugin layer for a game and it seems as though users wouldn't be able to import specifiers like these? Old school deno.land resolution or pure http(s) ones work just fine as it recursively tries to grab all the dependencies, but if someone has imported something from `npm:` or `jsr:` things will fail.

ERROR:  Rusty error: jsr imports are not allowed here: jsr:@std/assert
ERROR:  Rusty error: Could not find package 'npm:colors' from referrer 'http://localhost:8000/test.ts'.

```toml
default = ["node_experimental", "all_extensions"]
node_experimental = ["rustyscript/node_experimental"]
all_extensions = ["rustyscript/all_extensions"]

rustyscript = { version = "0.11.0", features = [
    "all_extensions",
    "node_experimental",
]}
```

I apologies _so much_ if this is just a user error on my part, I've made sure the `node_experimental` and `all_extensions` are enabled. I want to thank you so much for your work, it's been so much fun to use!
